/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MedicalDataRegistry } from "./MedicalDataRegistry";
export type { MedicalRecordAnchor } from "./MedicalRecordAnchor";
export type { PatientConsent } from "./PatientConsent";
export type { PrescriptionVerifier } from "./PrescriptionVerifier";
