/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IMedicalRecordAnchor {
  export type AnchoredRecordStruct = {
    dataHash: string;
    recordType: string;
    patientId: string;
    anchoredBy: AddressLike;
    timestamp: BigNumberish;
    exists: boolean;
    isRevoked: boolean;
  };

  export type AnchoredRecordStructOutput = [
    dataHash: string,
    recordType: string,
    patientId: string,
    anchoredBy: string,
    timestamp: bigint,
    exists: boolean,
    isRevoked: boolean
  ] & {
    dataHash: string;
    recordType: string;
    patientId: string;
    anchoredBy: string;
    timestamp: bigint;
    exists: boolean;
    isRevoked: boolean;
  };
}

export interface MedicalRecordAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "VERSION"
      | "addAuthorizedProvider"
      | "anchorFee"
      | "anchorHash"
      | "batchAnchorHash"
      | "getPatientRecordCount"
      | "getRecordByHash"
      | "getRecordsByPatient"
      | "getTotalRecords"
      | "isAuthorizedProvider"
      | "owner"
      | "pause"
      | "paused"
      | "platformWallet"
      | "removeAuthorizedProvider"
      | "renounceOwnership"
      | "revokeHash"
      | "setAnchorFee"
      | "setPlatformWallet"
      | "transferOwnership"
      | "unpause"
      | "verifyHash"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchAnchored"
      | "HashAnchored"
      | "HashRevoked"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addAuthorizedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "anchorFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anchorHash",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAnchorHash",
    values: [string[], string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientRecordCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordByHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordsByPatient",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeHash",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAnchorFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifyHash", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addAuthorizedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anchorFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchorHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchAnchorHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordsByPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAnchorFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace BatchAnchoredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    count: BigNumberish,
    anchoredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    count: bigint,
    anchoredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    count: bigint;
    anchoredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashAnchoredEvent {
  export type InputTuple = [
    txId: BytesLike,
    dataHash: string,
    recordType: string,
    patientId: string,
    anchoredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: string,
    dataHash: string,
    recordType: string,
    patientId: string,
    anchoredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: string;
    dataHash: string;
    recordType: string;
    patientId: string;
    anchoredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashRevokedEvent {
  export type InputTuple = [
    txId: BytesLike,
    dataHash: string,
    revokedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: string,
    dataHash: string,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: string;
    dataHash: string;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalRecordAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalRecordAnchor;
  waitForDeployment(): Promise<this>;

  interface: MedicalRecordAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  addAuthorizedProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  anchorFee: TypedContractMethod<[], [bigint], "view">;

  anchorHash: TypedContractMethod<
    [dataHash: string, recordType: string, patientId: string],
    [string],
    "nonpayable"
  >;

  batchAnchorHash: TypedContractMethod<
    [dataHashes: string[], recordTypes: string[], patientIds: string[]],
    [string],
    "nonpayable"
  >;

  getPatientRecordCount: TypedContractMethod<
    [patientId: string],
    [bigint],
    "view"
  >;

  getRecordByHash: TypedContractMethod<
    [dataHash: string],
    [IMedicalRecordAnchor.AnchoredRecordStructOutput],
    "view"
  >;

  getRecordsByPatient: TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { hashes: string[]; total: bigint }],
    "view"
  >;

  getTotalRecords: TypedContractMethod<[], [bigint], "view">;

  isAuthorizedProvider: TypedContractMethod<
    [provider: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  removeAuthorizedProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeHash: TypedContractMethod<
    [dataHash: string, reason: string],
    [void],
    "nonpayable"
  >;

  setAnchorFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setPlatformWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyHash: TypedContractMethod<
    [dataHash: string],
    [
      [boolean, bigint, string, boolean] & {
        exists: boolean;
        timestamp: bigint;
        anchoredBy: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addAuthorizedProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchorFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "anchorHash"
  ): TypedContractMethod<
    [dataHash: string, recordType: string, patientId: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchAnchorHash"
  ): TypedContractMethod<
    [dataHashes: string[], recordTypes: string[], patientIds: string[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPatientRecordCount"
  ): TypedContractMethod<[patientId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecordByHash"
  ): TypedContractMethod<
    [dataHash: string],
    [IMedicalRecordAnchor.AnchoredRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordsByPatient"
  ): TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { hashes: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedProvider"
  ): TypedContractMethod<[provider: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAuthorizedProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeHash"
  ): TypedContractMethod<
    [dataHash: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAnchorFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [dataHash: string],
    [
      [boolean, bigint, string, boolean] & {
        exists: boolean;
        timestamp: bigint;
        anchoredBy: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BatchAnchored"
  ): TypedContractEvent<
    BatchAnchoredEvent.InputTuple,
    BatchAnchoredEvent.OutputTuple,
    BatchAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "HashAnchored"
  ): TypedContractEvent<
    HashAnchoredEvent.InputTuple,
    HashAnchoredEvent.OutputTuple,
    HashAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "HashRevoked"
  ): TypedContractEvent<
    HashRevokedEvent.InputTuple,
    HashRevokedEvent.OutputTuple,
    HashRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BatchAnchored(bytes32,uint256,address,uint256)": TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
    BatchAnchored: TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;

    "HashAnchored(bytes32,string,string,string,address,uint256)": TypedContractEvent<
      HashAnchoredEvent.InputTuple,
      HashAnchoredEvent.OutputTuple,
      HashAnchoredEvent.OutputObject
    >;
    HashAnchored: TypedContractEvent<
      HashAnchoredEvent.InputTuple,
      HashAnchoredEvent.OutputTuple,
      HashAnchoredEvent.OutputObject
    >;

    "HashRevoked(bytes32,string,address,uint256)": TypedContractEvent<
      HashRevokedEvent.InputTuple,
      HashRevokedEvent.OutputTuple,
      HashRevokedEvent.OutputObject
    >;
    HashRevoked: TypedContractEvent<
      HashRevokedEvent.InputTuple,
      HashRevokedEvent.OutputTuple,
      HashRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
