/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MedicalDataRegistry {
  export type ProviderStruct = {
    providerAddress: AddressLike;
    name: string;
    providerType: string;
    isActive: boolean;
    registeredAt: BigNumberish;
  };

  export type ProviderStructOutput = [
    providerAddress: string,
    name: string,
    providerType: string,
    isActive: boolean,
    registeredAt: bigint
  ] & {
    providerAddress: string;
    name: string;
    providerType: string;
    isActive: boolean;
    registeredAt: bigint;
  };

  export type DataTransactionStruct = {
    txId: BytesLike;
    dataHash: string;
    dataType: string;
    operation: string;
    patientId: string;
    actor: AddressLike;
    targetProvider: AddressLike;
    timestamp: BigNumberish;
    metadata: string;
  };

  export type DataTransactionStructOutput = [
    txId: string,
    dataHash: string,
    dataType: string,
    operation: string,
    patientId: string,
    actor: string,
    targetProvider: string,
    timestamp: bigint,
    metadata: string
  ] & {
    txId: string;
    dataHash: string;
    dataType: string;
    operation: string;
    patientId: string;
    actor: string;
    targetProvider: string;
    timestamp: bigint;
    metadata: string;
  };
}

export interface MedicalDataRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateProvider"
      | "getAllProviders"
      | "getProvider"
      | "getStats"
      | "getTotalTransactions"
      | "getTransaction"
      | "getTransactionsByHash"
      | "getTransactionsByPatient"
      | "owner"
      | "pause"
      | "paused"
      | "recordTransaction"
      | "registerProvider"
      | "renounceOwnership"
      | "totalAnchoredHashes"
      | "totalConsents"
      | "totalPrescriptions"
      | "transferOwnership"
      | "unpause"
      | "updateStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "ProviderDeactivated"
      | "ProviderRegistered"
      | "StatsUpdated"
      | "TransactionRecorded"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateProvider",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTotalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionsByHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionsByPatient",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordTransaction",
    values: [string, string, string, string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAnchoredHashes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalConsents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPrescriptions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateStats",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionsByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionsByPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAnchoredHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalConsents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPrescriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStats",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderDeactivatedEvent {
  export type InputTuple = [providerAddress: AddressLike, reason: string];
  export type OutputTuple = [providerAddress: string, reason: string];
  export interface OutputObject {
    providerAddress: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [
    providerAddress: AddressLike,
    name: string,
    providerType: string
  ];
  export type OutputTuple = [
    providerAddress: string,
    name: string,
    providerType: string
  ];
  export interface OutputObject {
    providerAddress: string;
    name: string;
    providerType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatsUpdatedEvent {
  export type InputTuple = [
    totalAnchoredHashes: BigNumberish,
    totalConsents: BigNumberish,
    totalPrescriptions: BigNumberish
  ];
  export type OutputTuple = [
    totalAnchoredHashes: bigint,
    totalConsents: bigint,
    totalPrescriptions: bigint
  ];
  export interface OutputObject {
    totalAnchoredHashes: bigint;
    totalConsents: bigint;
    totalPrescriptions: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionRecordedEvent {
  export type InputTuple = [
    txId: BytesLike,
    dataType: string,
    operation: string,
    patientId: string,
    actor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: string,
    dataType: string,
    operation: string,
    patientId: string,
    actor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: string;
    dataType: string;
    operation: string;
    patientId: string;
    actor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalDataRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalDataRegistry;
  waitForDeployment(): Promise<this>;

  interface: MedicalDataRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateProvider: TypedContractMethod<
    [providerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  getAllProviders: TypedContractMethod<
    [],
    [MedicalDataRegistry.ProviderStructOutput[]],
    "view"
  >;

  getProvider: TypedContractMethod<
    [providerAddress: AddressLike],
    [MedicalDataRegistry.ProviderStructOutput],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _totalTransactions: bigint;
        _totalProviders: bigint;
        _anchoredHashes: bigint;
        _consents: bigint;
        _prescriptions: bigint;
      }
    ],
    "view"
  >;

  getTotalTransactions: TypedContractMethod<[], [bigint], "view">;

  getTransaction: TypedContractMethod<
    [txId: BytesLike],
    [MedicalDataRegistry.DataTransactionStructOutput],
    "view"
  >;

  getTransactionsByHash: TypedContractMethod<
    [dataHash: string],
    [string[]],
    "view"
  >;

  getTransactionsByPatient: TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [MedicalDataRegistry.DataTransactionStructOutput[], bigint] & {
        records: MedicalDataRegistry.DataTransactionStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordTransaction: TypedContractMethod<
    [
      dataHash: string,
      dataType: string,
      operation: string,
      patientId: string,
      targetProvider: AddressLike,
      metadata: string
    ],
    [string],
    "nonpayable"
  >;

  registerProvider: TypedContractMethod<
    [name: string, providerType: string],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalAnchoredHashes: TypedContractMethod<[], [bigint], "view">;

  totalConsents: TypedContractMethod<[], [bigint], "view">;

  totalPrescriptions: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateStats: TypedContractMethod<
    [
      _anchoredHashes: BigNumberish,
      _consents: BigNumberish,
      _prescriptions: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateProvider"
  ): TypedContractMethod<
    [providerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllProviders"
  ): TypedContractMethod<
    [],
    [MedicalDataRegistry.ProviderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProvider"
  ): TypedContractMethod<
    [providerAddress: AddressLike],
    [MedicalDataRegistry.ProviderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _totalTransactions: bigint;
        _totalProviders: bigint;
        _anchoredHashes: bigint;
        _consents: bigint;
        _prescriptions: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [txId: BytesLike],
    [MedicalDataRegistry.DataTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransactionsByHash"
  ): TypedContractMethod<[dataHash: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransactionsByPatient"
  ): TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [MedicalDataRegistry.DataTransactionStructOutput[], bigint] & {
        records: MedicalDataRegistry.DataTransactionStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordTransaction"
  ): TypedContractMethod<
    [
      dataHash: string,
      dataType: string,
      operation: string,
      patientId: string,
      targetProvider: AddressLike,
      metadata: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<
    [name: string, providerType: string],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAnchoredHashes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalConsents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPrescriptions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStats"
  ): TypedContractMethod<
    [
      _anchoredHashes: BigNumberish,
      _consents: BigNumberish,
      _prescriptions: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderDeactivated"
  ): TypedContractEvent<
    ProviderDeactivatedEvent.InputTuple,
    ProviderDeactivatedEvent.OutputTuple,
    ProviderDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StatsUpdated"
  ): TypedContractEvent<
    StatsUpdatedEvent.InputTuple,
    StatsUpdatedEvent.OutputTuple,
    StatsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionRecorded"
  ): TypedContractEvent<
    TransactionRecordedEvent.InputTuple,
    TransactionRecordedEvent.OutputTuple,
    TransactionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProviderDeactivated(address,string)": TypedContractEvent<
      ProviderDeactivatedEvent.InputTuple,
      ProviderDeactivatedEvent.OutputTuple,
      ProviderDeactivatedEvent.OutputObject
    >;
    ProviderDeactivated: TypedContractEvent<
      ProviderDeactivatedEvent.InputTuple,
      ProviderDeactivatedEvent.OutputTuple,
      ProviderDeactivatedEvent.OutputObject
    >;

    "ProviderRegistered(address,string,string)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;

    "StatsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      StatsUpdatedEvent.InputTuple,
      StatsUpdatedEvent.OutputTuple,
      StatsUpdatedEvent.OutputObject
    >;
    StatsUpdated: TypedContractEvent<
      StatsUpdatedEvent.InputTuple,
      StatsUpdatedEvent.OutputTuple,
      StatsUpdatedEvent.OutputObject
    >;

    "TransactionRecorded(bytes32,string,string,string,address,uint256)": TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
    TransactionRecorded: TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
