/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IPatientConsent {
  export type ConsentRecordStruct = {
    consentId: BytesLike;
    patientId: string;
    provider: AddressLike;
    recordType: string;
    accessLevel: string;
    grantedAt: BigNumberish;
    expiresAt: BigNumberish;
    isActive: boolean;
    isRevoked: boolean;
    revokedAt: BigNumberish;
    revokeReason: string;
  };

  export type ConsentRecordStructOutput = [
    consentId: string,
    patientId: string,
    provider: string,
    recordType: string,
    accessLevel: string,
    grantedAt: bigint,
    expiresAt: bigint,
    isActive: boolean,
    isRevoked: boolean,
    revokedAt: bigint,
    revokeReason: string
  ] & {
    consentId: string;
    patientId: string;
    provider: string;
    recordType: string;
    accessLevel: string;
    grantedAt: bigint;
    expiresAt: bigint;
    isActive: boolean;
    isRevoked: boolean;
    revokedAt: bigint;
    revokeReason: string;
  };
}

export interface PatientConsentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_EXPIRY"
      | "MAX_EXPIRY"
      | "checkConsent"
      | "getConsent"
      | "getPatientConsents"
      | "getProviderConsents"
      | "grantConsent"
      | "hasActiveConsent"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeConsent"
      | "transferOwnership"
      | "unpause"
      | "updateConsent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsentGranted"
      | "ConsentRevoked"
      | "ConsentUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkConsent",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientConsents",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderConsents",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantConsent",
    values: [string, AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveConsent",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateConsent",
    values: [BytesLike, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_EXPIRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_EXPIRY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConsent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPatientConsents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderConsents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateConsent",
    data: BytesLike
  ): Result;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    patientId: string,
    provider: AddressLike,
    recordType: string,
    accessLevel: string,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    patientId: string,
    provider: string,
    recordType: string,
    accessLevel: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    consentId: string;
    patientId: string;
    provider: string;
    recordType: string;
    accessLevel: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    patientId: string,
    provider: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    patientId: string,
    provider: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    consentId: string;
    patientId: string;
    provider: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentUpdatedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    newAccessLevel: string,
    newExpiresAt: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    newAccessLevel: string,
    newExpiresAt: bigint
  ];
  export interface OutputObject {
    consentId: string;
    newAccessLevel: string;
    newExpiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatientConsent extends BaseContract {
  connect(runner?: ContractRunner | null): PatientConsent;
  waitForDeployment(): Promise<this>;

  interface: PatientConsentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  MAX_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  checkConsent: TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [
      [boolean, string, bigint] & {
        hasAccess: boolean;
        accessLevel: string;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  getConsent: TypedContractMethod<
    [consentId: BytesLike],
    [IPatientConsent.ConsentRecordStructOutput],
    "view"
  >;

  getPatientConsents: TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  getProviderConsents: TypedContractMethod<
    [provider: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  grantConsent: TypedContractMethod<
    [
      patientId: string,
      provider: AddressLike,
      recordType: string,
      accessLevel: string,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  hasActiveConsent: TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeConsent: TypedContractMethod<
    [consentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateConsent: TypedContractMethod<
    [consentId: BytesLike, accessLevel: string, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkConsent"
  ): TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [
      [boolean, string, bigint] & {
        hasAccess: boolean;
        accessLevel: string;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsent"
  ): TypedContractMethod<
    [consentId: BytesLike],
    [IPatientConsent.ConsentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientConsents"
  ): TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderConsents"
  ): TypedContractMethod<
    [provider: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<
    [
      patientId: string,
      provider: AddressLike,
      recordType: string,
      accessLevel: string,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasActiveConsent"
  ): TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<
    [consentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateConsent"
  ): TypedContractMethod<
    [consentId: BytesLike, accessLevel: string, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentUpdated"
  ): TypedContractEvent<
    ConsentUpdatedEvent.InputTuple,
    ConsentUpdatedEvent.OutputTuple,
    ConsentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ConsentGranted(bytes32,string,address,string,string,uint256)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(bytes32,string,address,string,uint256)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;

    "ConsentUpdated(bytes32,string,uint256)": TypedContractEvent<
      ConsentUpdatedEvent.InputTuple,
      ConsentUpdatedEvent.OutputTuple,
      ConsentUpdatedEvent.OutputObject
    >;
    ConsentUpdated: TypedContractEvent<
      ConsentUpdatedEvent.InputTuple,
      ConsentUpdatedEvent.OutputTuple,
      ConsentUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
