/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PrescriptionVerifier {
  export type DispenseRecordStruct = {
    dispenseId: BytesLike;
    prescriptionId: BytesLike;
    pharmacy: AddressLike;
    pharmacist: AddressLike;
    quantity: BigNumberish;
    dispensedAt: BigNumberish;
    notes: string;
  };

  export type DispenseRecordStructOutput = [
    dispenseId: string,
    prescriptionId: string,
    pharmacy: string,
    pharmacist: string,
    quantity: bigint,
    dispensedAt: bigint,
    notes: string
  ] & {
    dispenseId: string;
    prescriptionId: string;
    pharmacy: string;
    pharmacist: string;
    quantity: bigint;
    dispensedAt: bigint;
    notes: string;
  };

  export type PrescriptionRecordStruct = {
    prescriptionId: BytesLike;
    dataHash: string;
    patientId: string;
    doctor: AddressLike;
    pharmacy: AddressLike;
    drugName: string;
    status: string;
    issuedAt: BigNumberish;
    expiresAt: BigNumberish;
    dispensedAt: BigNumberish;
    refillsAllowed: BigNumberish;
    refillsUsed: BigNumberish;
    exists: boolean;
  };

  export type PrescriptionRecordStructOutput = [
    prescriptionId: string,
    dataHash: string,
    patientId: string,
    doctor: string,
    pharmacy: string,
    drugName: string,
    status: string,
    issuedAt: bigint,
    expiresAt: bigint,
    dispensedAt: bigint,
    refillsAllowed: bigint,
    refillsUsed: bigint,
    exists: boolean
  ] & {
    prescriptionId: string;
    dataHash: string;
    patientId: string;
    doctor: string;
    pharmacy: string;
    drugName: string;
    status: string;
    issuedAt: bigint;
    expiresAt: bigint;
    dispensedAt: bigint;
    refillsAllowed: bigint;
    refillsUsed: bigint;
    exists: boolean;
  };
}

export interface PrescriptionVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuthorizedDoctor"
      | "addAuthorizedPharmacy"
      | "cancelPrescription"
      | "createPrescription"
      | "dispensePrescription"
      | "getDispenseHistory"
      | "getPatientPrescriptions"
      | "getPrescription"
      | "isAuthorizedDoctor"
      | "isAuthorizedPharmacy"
      | "owner"
      | "pause"
      | "paused"
      | "removeAuthorizedDoctor"
      | "removeAuthorizedPharmacy"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "verifyByHash"
      | "verifyPrescription"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "PrescriptionCancelled"
      | "PrescriptionCreated"
      | "PrescriptionDispensed"
      | "PrescriptionVerified"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuthorizedDoctor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthorizedPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPrescription",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createPrescription",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dispensePrescription",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDispenseHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientPrescriptions",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrescription",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedDoctor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedDoctor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedPharmacy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyByHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPrescription",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAuthorizedDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAuthorizedPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispensePrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDispenseHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientPrescriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedDoctor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedPharmacy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPrescription",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionCancelledEvent {
  export type InputTuple = [
    prescriptionId: BytesLike,
    cancelledBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    prescriptionId: string,
    cancelledBy: string,
    reason: string
  ];
  export interface OutputObject {
    prescriptionId: string;
    cancelledBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionCreatedEvent {
  export type InputTuple = [
    prescriptionId: BytesLike,
    patientId: string,
    doctor: AddressLike,
    drugName: string,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    prescriptionId: string,
    patientId: string,
    doctor: string,
    drugName: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    prescriptionId: string;
    patientId: string;
    doctor: string;
    drugName: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionDispensedEvent {
  export type InputTuple = [
    dispenseId: BytesLike,
    prescriptionId: BytesLike,
    pharmacy: AddressLike,
    quantity: BigNumberish,
    remainingRefills: BigNumberish
  ];
  export type OutputTuple = [
    dispenseId: string,
    prescriptionId: string,
    pharmacy: string,
    quantity: bigint,
    remainingRefills: bigint
  ];
  export interface OutputObject {
    dispenseId: string;
    prescriptionId: string;
    pharmacy: string;
    quantity: bigint;
    remainingRefills: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrescriptionVerifiedEvent {
  export type InputTuple = [
    prescriptionId: BytesLike,
    isValid: boolean,
    verifiedBy: AddressLike
  ];
  export type OutputTuple = [
    prescriptionId: string,
    isValid: boolean,
    verifiedBy: string
  ];
  export interface OutputObject {
    prescriptionId: string;
    isValid: boolean;
    verifiedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrescriptionVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): PrescriptionVerifier;
  waitForDeployment(): Promise<this>;

  interface: PrescriptionVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuthorizedDoctor: TypedContractMethod<
    [doctor: AddressLike],
    [void],
    "nonpayable"
  >;

  addAuthorizedPharmacy: TypedContractMethod<
    [pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelPrescription: TypedContractMethod<
    [prescriptionId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  createPrescription: TypedContractMethod<
    [
      dataHash: string,
      patientId: string,
      drugName: string,
      expiresAt: BigNumberish,
      refillsAllowed: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  dispensePrescription: TypedContractMethod<
    [prescriptionId: BytesLike, quantity: BigNumberish, notes: string],
    [string],
    "nonpayable"
  >;

  getDispenseHistory: TypedContractMethod<
    [prescriptionId: BytesLike],
    [PrescriptionVerifier.DispenseRecordStructOutput[]],
    "view"
  >;

  getPatientPrescriptions: TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [PrescriptionVerifier.PrescriptionRecordStructOutput[], bigint] & {
        records: PrescriptionVerifier.PrescriptionRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  getPrescription: TypedContractMethod<
    [prescriptionId: BytesLike],
    [PrescriptionVerifier.PrescriptionRecordStructOutput],
    "view"
  >;

  isAuthorizedDoctor: TypedContractMethod<
    [doctor: AddressLike],
    [boolean],
    "view"
  >;

  isAuthorizedPharmacy: TypedContractMethod<
    [pharmacy: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  removeAuthorizedDoctor: TypedContractMethod<
    [doctor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeAuthorizedPharmacy: TypedContractMethod<
    [pharmacy: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyByHash: TypedContractMethod<
    [dataHash: string],
    [[boolean, string] & { isValid: boolean; prescriptionId: string }],
    "view"
  >;

  verifyPrescription: TypedContractMethod<
    [prescriptionId: BytesLike],
    [
      [boolean, string, string, bigint, bigint, bigint, string] & {
        isValid: boolean;
        status: string;
        drugName: string;
        issuedAt: bigint;
        expiresAt: bigint;
        refillsRemaining: bigint;
        doctor: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuthorizedDoctor"
  ): TypedContractMethod<[doctor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addAuthorizedPharmacy"
  ): TypedContractMethod<[pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPrescription"
  ): TypedContractMethod<
    [prescriptionId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPrescription"
  ): TypedContractMethod<
    [
      dataHash: string,
      patientId: string,
      drugName: string,
      expiresAt: BigNumberish,
      refillsAllowed: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dispensePrescription"
  ): TypedContractMethod<
    [prescriptionId: BytesLike, quantity: BigNumberish, notes: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDispenseHistory"
  ): TypedContractMethod<
    [prescriptionId: BytesLike],
    [PrescriptionVerifier.DispenseRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientPrescriptions"
  ): TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [PrescriptionVerifier.PrescriptionRecordStructOutput[], bigint] & {
        records: PrescriptionVerifier.PrescriptionRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrescription"
  ): TypedContractMethod<
    [prescriptionId: BytesLike],
    [PrescriptionVerifier.PrescriptionRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedDoctor"
  ): TypedContractMethod<[doctor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedPharmacy"
  ): TypedContractMethod<[pharmacy: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeAuthorizedDoctor"
  ): TypedContractMethod<[doctor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAuthorizedPharmacy"
  ): TypedContractMethod<[pharmacy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyByHash"
  ): TypedContractMethod<
    [dataHash: string],
    [[boolean, string] & { isValid: boolean; prescriptionId: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyPrescription"
  ): TypedContractMethod<
    [prescriptionId: BytesLike],
    [
      [boolean, string, string, bigint, bigint, bigint, string] & {
        isValid: boolean;
        status: string;
        drugName: string;
        issuedAt: bigint;
        expiresAt: bigint;
        refillsRemaining: bigint;
        doctor: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionCancelled"
  ): TypedContractEvent<
    PrescriptionCancelledEvent.InputTuple,
    PrescriptionCancelledEvent.OutputTuple,
    PrescriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionCreated"
  ): TypedContractEvent<
    PrescriptionCreatedEvent.InputTuple,
    PrescriptionCreatedEvent.OutputTuple,
    PrescriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionDispensed"
  ): TypedContractEvent<
    PrescriptionDispensedEvent.InputTuple,
    PrescriptionDispensedEvent.OutputTuple,
    PrescriptionDispensedEvent.OutputObject
  >;
  getEvent(
    key: "PrescriptionVerified"
  ): TypedContractEvent<
    PrescriptionVerifiedEvent.InputTuple,
    PrescriptionVerifiedEvent.OutputTuple,
    PrescriptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PrescriptionCancelled(bytes32,address,string)": TypedContractEvent<
      PrescriptionCancelledEvent.InputTuple,
      PrescriptionCancelledEvent.OutputTuple,
      PrescriptionCancelledEvent.OutputObject
    >;
    PrescriptionCancelled: TypedContractEvent<
      PrescriptionCancelledEvent.InputTuple,
      PrescriptionCancelledEvent.OutputTuple,
      PrescriptionCancelledEvent.OutputObject
    >;

    "PrescriptionCreated(bytes32,string,address,string,uint256)": TypedContractEvent<
      PrescriptionCreatedEvent.InputTuple,
      PrescriptionCreatedEvent.OutputTuple,
      PrescriptionCreatedEvent.OutputObject
    >;
    PrescriptionCreated: TypedContractEvent<
      PrescriptionCreatedEvent.InputTuple,
      PrescriptionCreatedEvent.OutputTuple,
      PrescriptionCreatedEvent.OutputObject
    >;

    "PrescriptionDispensed(bytes32,bytes32,address,uint256,uint256)": TypedContractEvent<
      PrescriptionDispensedEvent.InputTuple,
      PrescriptionDispensedEvent.OutputTuple,
      PrescriptionDispensedEvent.OutputObject
    >;
    PrescriptionDispensed: TypedContractEvent<
      PrescriptionDispensedEvent.InputTuple,
      PrescriptionDispensedEvent.OutputTuple,
      PrescriptionDispensedEvent.OutputObject
    >;

    "PrescriptionVerified(bytes32,bool,address)": TypedContractEvent<
      PrescriptionVerifiedEvent.InputTuple,
      PrescriptionVerifiedEvent.OutputTuple,
      PrescriptionVerifiedEvent.OutputObject
    >;
    PrescriptionVerified: TypedContractEvent<
      PrescriptionVerifiedEvent.InputTuple,
      PrescriptionVerifiedEvent.OutputTuple,
      PrescriptionVerifiedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
