/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "IMedicalRecordAnchor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMedicalRecordAnchor__factory>;
    getContractFactory(
      name: "IPatientConsent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPatientConsent__factory>;
    getContractFactory(
      name: "MedicalDataRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MedicalDataRegistry__factory>;
    getContractFactory(
      name: "MedicalRecordAnchor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MedicalRecordAnchor__factory>;
    getContractFactory(
      name: "PatientConsent",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PatientConsent__factory>;
    getContractFactory(
      name: "PrescriptionVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrescriptionVerifier__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "IMedicalRecordAnchor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMedicalRecordAnchor>;
    getContractAt(
      name: "IPatientConsent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPatientConsent>;
    getContractAt(
      name: "MedicalDataRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MedicalDataRegistry>;
    getContractAt(
      name: "MedicalRecordAnchor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MedicalRecordAnchor>;
    getContractAt(
      name: "PatientConsent",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PatientConsent>;
    getContractAt(
      name: "PrescriptionVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrescriptionVerifier>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "IMedicalRecordAnchor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMedicalRecordAnchor>;
    deployContract(
      name: "IPatientConsent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPatientConsent>;
    deployContract(
      name: "MedicalDataRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MedicalDataRegistry>;
    deployContract(
      name: "MedicalRecordAnchor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MedicalRecordAnchor>;
    deployContract(
      name: "PatientConsent",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientConsent>;
    deployContract(
      name: "PrescriptionVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrescriptionVerifier>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "IMedicalRecordAnchor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMedicalRecordAnchor>;
    deployContract(
      name: "IPatientConsent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPatientConsent>;
    deployContract(
      name: "MedicalDataRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MedicalDataRegistry>;
    deployContract(
      name: "MedicalRecordAnchor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MedicalRecordAnchor>;
    deployContract(
      name: "PatientConsent",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientConsent>;
    deployContract(
      name: "PrescriptionVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrescriptionVerifier>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
