/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { MedicalDataRegistry__factory } from "./MedicalDataRegistry__factory";
export { MedicalRecordAnchor__factory } from "./MedicalRecordAnchor__factory";
export { PatientConsent__factory } from "./PatientConsent__factory";
export { PrescriptionVerifier__factory } from "./PrescriptionVerifier__factory";
