/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMedicalRecordAnchor,
  IMedicalRecordAnchorInterface,
} from "../../../contracts/interfaces/IMedicalRecordAnchor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "anchoredBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "BatchAnchored",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "txId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "dataHash",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "recordType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "anchoredBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HashAnchored",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "txId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "dataHash",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "revokedBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HashRevoked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "dataHash",
        type: "string",
      },
      {
        internalType: "string",
        name: "recordType",
        type: "string",
      },
      {
        internalType: "string",
        name: "patientId",
        type: "string",
      },
    ],
    name: "anchorHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string[]",
        name: "dataHashes",
        type: "string[]",
      },
      {
        internalType: "string[]",
        name: "recordTypes",
        type: "string[]",
      },
      {
        internalType: "string[]",
        name: "patientIds",
        type: "string[]",
      },
    ],
    name: "batchAnchorHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "dataHash",
        type: "string",
      },
    ],
    name: "getRecordByHash",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "dataHash",
            type: "string",
          },
          {
            internalType: "string",
            name: "recordType",
            type: "string",
          },
          {
            internalType: "string",
            name: "patientId",
            type: "string",
          },
          {
            internalType: "address",
            name: "anchoredBy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "exists",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isRevoked",
            type: "bool",
          },
        ],
        internalType: "struct IMedicalRecordAnchor.AnchoredRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getRecordsByPatient",
    outputs: [
      {
        internalType: "string[]",
        name: "hashes",
        type: "string[]",
      },
      {
        internalType: "uint256",
        name: "total",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalRecords",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "isAuthorizedProvider",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "dataHash",
        type: "string",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "revokeHash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "dataHash",
        type: "string",
      },
    ],
    name: "verifyHash",
    outputs: [
      {
        internalType: "bool",
        name: "exists",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "anchoredBy",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isRevoked",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMedicalRecordAnchor__factory {
  static readonly abi = _abi;
  static createInterface(): IMedicalRecordAnchorInterface {
    return new Interface(_abi) as IMedicalRecordAnchorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMedicalRecordAnchor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMedicalRecordAnchor;
  }
}
