/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMedicalRecordAnchor__factory } from "./IMedicalRecordAnchor__factory";
export { IPatientConsent__factory } from "./IPatientConsent__factory";
