/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPatientConsent,
  IPatientConsentInterface,
} from "../../../contracts/interfaces/IPatientConsent";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "consentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "recordType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "accessLevel",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "ConsentGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "consentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ConsentRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "consentId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "newAccessLevel",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newExpiresAt",
        type: "uint256",
      },
    ],
    name: "ConsentUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "string",
        name: "recordType",
        type: "string",
      },
    ],
    name: "checkConsent",
    outputs: [
      {
        internalType: "bool",
        name: "hasAccess",
        type: "bool",
      },
      {
        internalType: "string",
        name: "accessLevel",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getPatientConsents",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "consentId",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "patientId",
            type: "string",
          },
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "string",
            name: "recordType",
            type: "string",
          },
          {
            internalType: "string",
            name: "accessLevel",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "grantedAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expiresAt",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isRevoked",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "revokedAt",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "revokeReason",
            type: "string",
          },
        ],
        internalType: "struct IPatientConsent.ConsentRecord[]",
        name: "records",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "total",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getProviderConsents",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "consentId",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "patientId",
            type: "string",
          },
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "string",
            name: "recordType",
            type: "string",
          },
          {
            internalType: "string",
            name: "accessLevel",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "grantedAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expiresAt",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isRevoked",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "revokedAt",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "revokeReason",
            type: "string",
          },
        ],
        internalType: "struct IPatientConsent.ConsentRecord[]",
        name: "records",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "total",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "string",
        name: "recordType",
        type: "string",
      },
      {
        internalType: "string",
        name: "accessLevel",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "grantConsent",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "patientId",
        type: "string",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "string",
        name: "recordType",
        type: "string",
      },
    ],
    name: "hasActiveConsent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "consentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "revokeConsent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "consentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "accessLevel",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "expiresAt",
        type: "uint256",
      },
    ],
    name: "updateConsent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPatientConsent__factory {
  static readonly abi = _abi;
  static createInterface(): IPatientConsentInterface {
    return new Interface(_abi) as IPatientConsentInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPatientConsent {
    return new Contract(address, _abi, runner) as unknown as IPatientConsent;
  }
}
