/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMedicalRecordAnchor {
  export type AnchoredRecordStruct = {
    dataHash: string;
    recordType: string;
    patientId: string;
    anchoredBy: AddressLike;
    timestamp: BigNumberish;
    exists: boolean;
    isRevoked: boolean;
  };

  export type AnchoredRecordStructOutput = [
    dataHash: string,
    recordType: string,
    patientId: string,
    anchoredBy: string,
    timestamp: bigint,
    exists: boolean,
    isRevoked: boolean
  ] & {
    dataHash: string;
    recordType: string;
    patientId: string;
    anchoredBy: string;
    timestamp: bigint;
    exists: boolean;
    isRevoked: boolean;
  };
}

export interface IMedicalRecordAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorHash"
      | "batchAnchorHash"
      | "getRecordByHash"
      | "getRecordsByPatient"
      | "getTotalRecords"
      | "isAuthorizedProvider"
      | "revokeHash"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BatchAnchored" | "HashAnchored" | "HashRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorHash",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAnchorHash",
    values: [string[], string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordByHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordsByPatient",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeHash",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "verifyHash", values: [string]): string;

  decodeFunctionResult(functionFragment: "anchorHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchAnchorHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordsByPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace BatchAnchoredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    count: BigNumberish,
    anchoredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    count: bigint,
    anchoredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    count: bigint;
    anchoredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashAnchoredEvent {
  export type InputTuple = [
    txId: BytesLike,
    dataHash: string,
    recordType: string,
    patientId: string,
    anchoredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: string,
    dataHash: string,
    recordType: string,
    patientId: string,
    anchoredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: string;
    dataHash: string;
    recordType: string;
    patientId: string;
    anchoredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashRevokedEvent {
  export type InputTuple = [
    txId: BytesLike,
    dataHash: string,
    revokedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    txId: string,
    dataHash: string,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    txId: string;
    dataHash: string;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMedicalRecordAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): IMedicalRecordAnchor;
  waitForDeployment(): Promise<this>;

  interface: IMedicalRecordAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorHash: TypedContractMethod<
    [dataHash: string, recordType: string, patientId: string],
    [string],
    "nonpayable"
  >;

  batchAnchorHash: TypedContractMethod<
    [dataHashes: string[], recordTypes: string[], patientIds: string[]],
    [string],
    "nonpayable"
  >;

  getRecordByHash: TypedContractMethod<
    [dataHash: string],
    [IMedicalRecordAnchor.AnchoredRecordStructOutput],
    "view"
  >;

  getRecordsByPatient: TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { hashes: string[]; total: bigint }],
    "view"
  >;

  getTotalRecords: TypedContractMethod<[], [bigint], "view">;

  isAuthorizedProvider: TypedContractMethod<
    [provider: AddressLike],
    [boolean],
    "view"
  >;

  revokeHash: TypedContractMethod<
    [dataHash: string, reason: string],
    [void],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [dataHash: string],
    [
      [boolean, bigint, string, boolean] & {
        exists: boolean;
        timestamp: bigint;
        anchoredBy: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorHash"
  ): TypedContractMethod<
    [dataHash: string, recordType: string, patientId: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchAnchorHash"
  ): TypedContractMethod<
    [dataHashes: string[], recordTypes: string[], patientIds: string[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecordByHash"
  ): TypedContractMethod<
    [dataHash: string],
    [IMedicalRecordAnchor.AnchoredRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordsByPatient"
  ): TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [[string[], bigint] & { hashes: string[]; total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedProvider"
  ): TypedContractMethod<[provider: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeHash"
  ): TypedContractMethod<
    [dataHash: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [dataHash: string],
    [
      [boolean, bigint, string, boolean] & {
        exists: boolean;
        timestamp: bigint;
        anchoredBy: string;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BatchAnchored"
  ): TypedContractEvent<
    BatchAnchoredEvent.InputTuple,
    BatchAnchoredEvent.OutputTuple,
    BatchAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "HashAnchored"
  ): TypedContractEvent<
    HashAnchoredEvent.InputTuple,
    HashAnchoredEvent.OutputTuple,
    HashAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "HashRevoked"
  ): TypedContractEvent<
    HashRevokedEvent.InputTuple,
    HashRevokedEvent.OutputTuple,
    HashRevokedEvent.OutputObject
  >;

  filters: {
    "BatchAnchored(bytes32,uint256,address,uint256)": TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;
    BatchAnchored: TypedContractEvent<
      BatchAnchoredEvent.InputTuple,
      BatchAnchoredEvent.OutputTuple,
      BatchAnchoredEvent.OutputObject
    >;

    "HashAnchored(bytes32,string,string,string,address,uint256)": TypedContractEvent<
      HashAnchoredEvent.InputTuple,
      HashAnchoredEvent.OutputTuple,
      HashAnchoredEvent.OutputObject
    >;
    HashAnchored: TypedContractEvent<
      HashAnchoredEvent.InputTuple,
      HashAnchoredEvent.OutputTuple,
      HashAnchoredEvent.OutputObject
    >;

    "HashRevoked(bytes32,string,address,uint256)": TypedContractEvent<
      HashRevokedEvent.InputTuple,
      HashRevokedEvent.OutputTuple,
      HashRevokedEvent.OutputObject
    >;
    HashRevoked: TypedContractEvent<
      HashRevokedEvent.InputTuple,
      HashRevokedEvent.OutputTuple,
      HashRevokedEvent.OutputObject
    >;
  };
}
