/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMedicalRecordAnchor } from "./IMedicalRecordAnchor";
export type { IPatientConsent } from "./IPatientConsent";
