/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPatientConsent {
  export type ConsentRecordStruct = {
    consentId: BytesLike;
    patientId: string;
    provider: AddressLike;
    recordType: string;
    accessLevel: string;
    grantedAt: BigNumberish;
    expiresAt: BigNumberish;
    isActive: boolean;
    isRevoked: boolean;
    revokedAt: BigNumberish;
    revokeReason: string;
  };

  export type ConsentRecordStructOutput = [
    consentId: string,
    patientId: string,
    provider: string,
    recordType: string,
    accessLevel: string,
    grantedAt: bigint,
    expiresAt: bigint,
    isActive: boolean,
    isRevoked: boolean,
    revokedAt: bigint,
    revokeReason: string
  ] & {
    consentId: string;
    patientId: string;
    provider: string;
    recordType: string;
    accessLevel: string;
    grantedAt: bigint;
    expiresAt: bigint;
    isActive: boolean;
    isRevoked: boolean;
    revokedAt: bigint;
    revokeReason: string;
  };
}

export interface IPatientConsentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkConsent"
      | "getPatientConsents"
      | "getProviderConsents"
      | "grantConsent"
      | "hasActiveConsent"
      | "revokeConsent"
      | "updateConsent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsentGranted"
      | "ConsentRevoked"
      | "ConsentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkConsent",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientConsents",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderConsents",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantConsent",
    values: [string, AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveConsent",
    values: [string, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConsent",
    values: [BytesLike, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientConsents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderConsents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConsent",
    data: BytesLike
  ): Result;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    patientId: string,
    provider: AddressLike,
    recordType: string,
    accessLevel: string,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    patientId: string,
    provider: string,
    recordType: string,
    accessLevel: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    consentId: string;
    patientId: string;
    provider: string;
    recordType: string;
    accessLevel: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    patientId: string,
    provider: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    patientId: string,
    provider: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    consentId: string;
    patientId: string;
    provider: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentUpdatedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    newAccessLevel: string,
    newExpiresAt: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    newAccessLevel: string,
    newExpiresAt: bigint
  ];
  export interface OutputObject {
    consentId: string;
    newAccessLevel: string;
    newExpiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPatientConsent extends BaseContract {
  connect(runner?: ContractRunner | null): IPatientConsent;
  waitForDeployment(): Promise<this>;

  interface: IPatientConsentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkConsent: TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [
      [boolean, string, bigint] & {
        hasAccess: boolean;
        accessLevel: string;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  getPatientConsents: TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  getProviderConsents: TypedContractMethod<
    [provider: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;

  grantConsent: TypedContractMethod<
    [
      patientId: string,
      provider: AddressLike,
      recordType: string,
      accessLevel: string,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  hasActiveConsent: TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [boolean],
    "view"
  >;

  revokeConsent: TypedContractMethod<
    [consentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  updateConsent: TypedContractMethod<
    [consentId: BytesLike, accessLevel: string, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkConsent"
  ): TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [
      [boolean, string, bigint] & {
        hasAccess: boolean;
        accessLevel: string;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPatientConsents"
  ): TypedContractMethod<
    [patientId: string, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProviderConsents"
  ): TypedContractMethod<
    [provider: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [
      [IPatientConsent.ConsentRecordStructOutput[], bigint] & {
        records: IPatientConsent.ConsentRecordStructOutput[];
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<
    [
      patientId: string,
      provider: AddressLike,
      recordType: string,
      accessLevel: string,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasActiveConsent"
  ): TypedContractMethod<
    [patientId: string, provider: AddressLike, recordType: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<
    [consentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateConsent"
  ): TypedContractMethod<
    [consentId: BytesLike, accessLevel: string, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentUpdated"
  ): TypedContractEvent<
    ConsentUpdatedEvent.InputTuple,
    ConsentUpdatedEvent.OutputTuple,
    ConsentUpdatedEvent.OutputObject
  >;

  filters: {
    "ConsentGranted(bytes32,string,address,string,string,uint256)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(bytes32,string,address,string,uint256)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;

    "ConsentUpdated(bytes32,string,uint256)": TypedContractEvent<
      ConsentUpdatedEvent.InputTuple,
      ConsentUpdatedEvent.OutputTuple,
      ConsentUpdatedEvent.OutputObject
    >;
    ConsentUpdated: TypedContractEvent<
      ConsentUpdatedEvent.InputTuple,
      ConsentUpdatedEvent.OutputTuple,
      ConsentUpdatedEvent.OutputObject
    >;
  };
}
